// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeow0BpkMcXWgmSWfMD2KgnlSz7ikmWEE',
    appId: '1:948491121904:web:82a97670f53511db88be35',
    messagingSenderId: '948491121904',
    projectId: 'improove-a5eaa',
    authDomain: 'improove-a5eaa.firebaseapp.com',
    storageBucket: 'improove-a5eaa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARRqtxjfHlQDsZFD5tznOLYACvb7a3myg',
    appId: '1:948491121904:android:c6199e07fa7ab66488be35',
    messagingSenderId: '948491121904',
    projectId: 'improove-a5eaa',
    storageBucket: 'improove-a5eaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6mzNj3cXm5J5wQEIHArvGt4RQgbD0fkI',
    appId: '1:948491121904:ios:f257db58308de5b088be35',
    messagingSenderId: '948491121904',
    projectId: 'improove-a5eaa',
    storageBucket: 'improove-a5eaa.appspot.com',
    iosBundleId: 'com.example.frontendImproove',
  );
}
